// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingApp.DataLayer;

#nullable disable

namespace TradingApp.DataLayer.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260616223311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingApp.DataLayer.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "USD",
                            Country = "United States",
                            Name = "Dollar"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "ILS",
                            Country = "Israel",
                            Name = "Shekel"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "EUR",
                            Country = "Europe",
                            Name = "Euro"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "GBP",
                            Country = "Great Britain",
                            Name = "Pound"
                        });
                });

            modelBuilder.Entity("TradingApp.DataLayer.Models.CurrencyPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuoteCurrencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId")
                        .IsUnique();

                    b.ToTable("CurrencyPairs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseCurrencyId = 1,
                            CurrentValue = 3.6500m,
                            MaxValue = 3.7000m,
                            MinValue = 3.6000m,
                            QuoteCurrencyId = 2
                        },
                        new
                        {
                            Id = 2,
                            BaseCurrencyId = 3,
                            CurrentValue = 1.0800m,
                            MaxValue = 1.1200m,
                            MinValue = 1.0500m,
                            QuoteCurrencyId = 1
                        },
                        new
                        {
                            Id = 3,
                            BaseCurrencyId = 4,
                            CurrentValue = 4.6200m,
                            MaxValue = 4.7000m,
                            MinValue = 4.5500m,
                            QuoteCurrencyId = 2
                        });
                });

            modelBuilder.Entity("TradingApp.DataLayer.Models.CurrencyPair", b =>
                {
                    b.HasOne("TradingApp.DataLayer.Models.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingApp.DataLayer.Models.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });
#pragma warning restore 612, 618
        }
    }
}
